import yaml
import os

OUT = "/kpi_registry"
os.makedirs(OUT, exist_ok=True)

KPIS = {

"ai_roi": {
    "name": "AI ROI",
    "category": "Value Creation",
    "tier": "executive",
    "description": "Measures the total financial return generated per dollar of AI investment across the portfolio.",
    "business_value": "Determines whether AI investments create measurable financial value and guides capital allocation decisions.",
    "formula": "(ai_revenue + cost_savings) / total_ai_spend",
    "unit": "ratio",
    "aggregation": "portfolio_weighted_average",
    "frequency": "monthly",
    "required_facts": ["ai_revenue", "cost_savings", "total_ai_spend"],
    "derived_facts": [],
    "required_documents": ["financial", "project_portfolio"],
    "dependencies": ["ai_revenue", "total_ai_spend", "cost_savings"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 5.0, "good": 3.0, "warning": 1.5, "critical": 1.0},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.85},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["cxo", "operating_partner"],
    "dashboard_visibility": ["executive_dashboard", "benchmark_dashboard"],
    "example_calculation": "ai_revenue=5M, cost_savings=2M, total_ai_spend=1M => ROI = 7.0",
    "status": "active"
},

"ai_revenue": {
    "name": "AI Revenue",
    "category": "Revenue Growth",
    "tier": "executive",
    "description": "Total incremental revenue directly attributable to AI-driven products, features, and services.",
    "business_value": "Quantifies AI's top-line contribution and justifies continued investment.",
    "formula": "direct_ai_revenue + ai_assisted_revenue + pipeline_influenced_revenue",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["direct_ai_revenue", "ai_assisted_revenue", "pipeline_influenced_revenue"],
    "derived_facts": [],
    "required_documents": ["financial", "crm"],
    "dependencies": ["direct_ai_revenue", "ai_assisted_revenue", "pipeline_influenced_revenue"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 10000000, "good": 5000000, "warning": 2000000, "critical": 500000},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.90},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["cxo", "business_lead"],
    "dashboard_visibility": ["executive_dashboard", "revenue_dashboard"],
    "example_calculation": "direct=14.1M, assisted=6.4M, pipeline=18.9M => total=39.4M (portfolio-wide; per PortCo varies)",
    "status": "active"
},

"ebitda_uplift": {
    "name": "EBITDA Uplift",
    "category": "Value Creation",
    "tier": "executive",
    "description": "Percentage point improvement in EBITDA margin attributable to AI-driven cost reduction and process efficiency.",
    "business_value": "Directly links AI initiatives to PE value creation through margin expansion.",
    "formula": "(ebitda_post_ai - ebitda_pre_ai) / revenue_base * 100",
    "unit": "percentage_points",
    "aggregation": "portfolio_weighted_average",
    "frequency": "quarterly",
    "required_facts": ["ebitda_post_ai", "ebitda_pre_ai", "revenue_base"],
    "derived_facts": ["ebitda_delta"],
    "required_documents": ["financial", "board_deck"],
    "dependencies": ["ebitda_post_ai", "ebitda_pre_ai", "revenue_base"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 15.0, "good": 8.0, "warning": 3.0, "critical": 0.0},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.85},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["cxo", "operating_partner"],
    "dashboard_visibility": ["executive_dashboard"],
    "example_calculation": "ebitda_post=25M, ebitda_pre=21M, revenue=100M => uplift=4.0pp",
    "status": "active"
},

"cost_savings": {
    "name": "Cost Savings (OpEx)",
    "category": "Value Creation",
    "tier": "executive",
    "description": "Realized reduction in operational expenses resulting from AI deployment vs pre-AI baseline.",
    "business_value": "Validates AI's role in margin improvement through measurable OpEx reduction.",
    "formula": "opex_pre_ai_baseline - opex_current_period",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["opex_pre_ai_baseline", "opex_current_period"],
    "derived_facts": [],
    "required_documents": ["financial", "operations"],
    "dependencies": ["opex_pre_ai_baseline", "opex_current_period"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 5000000, "good": 2000000, "warning": 500000, "critical": 0},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["operating_partner", "cfo"],
    "dashboard_visibility": ["executive_dashboard", "finops_dashboard"],
    "example_calculation": "opex_pre=50M, opex_current=37.2M => savings=12.8M",
    "status": "active"
},

"productivity_gain": {
    "name": "Human Productivity Gains",
    "category": "Adoption",
    "tier": "operational",
    "description": "Average percentage increase in output per FTE across AI-enabled departments.",
    "business_value": "Demonstrates workforce efficiency gains from AI copilots and automation.",
    "formula": "(output_post_ai_per_fte - output_pre_ai_per_fte) / output_pre_ai_per_fte * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["output_post_ai_per_fte", "output_pre_ai_per_fte"],
    "derived_facts": [],
    "required_documents": ["hr", "operations"],
    "dependencies": ["output_post_ai_per_fte", "output_pre_ai_per_fte"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 40, "good": 25, "warning": 10, "critical": 0},
    "data_quality": {"minimum_coverage": 70, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["operating_partner", "business_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "output_pre=100 units/FTE, output_post=132 => gain=32%",
    "status": "active"
},

"payback_period": {
    "name": "AI Payback Period",
    "category": "Value Creation",
    "tier": "executive",
    "description": "Number of months required to recoup total AI investment from cumulative returns.",
    "business_value": "Provides LP-ready measure of investment recovery timeline.",
    "formula": "total_ai_spend / ((ai_revenue + cost_savings) / 12)",
    "unit": "months",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["total_ai_spend", "ai_revenue", "cost_savings"],
    "derived_facts": ["monthly_ai_return"],
    "required_documents": ["financial"],
    "dependencies": ["total_ai_spend", "ai_revenue", "cost_savings"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 6, "good": 12, "warning": 24, "critical": 36},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.85},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["cxo", "operating_partner"],
    "dashboard_visibility": ["executive_dashboard"],
    "example_calculation": "spend=10M, monthly_return=1.17M => payback=8.5 months",
    "status": "active"
},

"portfolio_ai_adoption_score": {
    "name": "Portfolio AI Adoption Score",
    "category": "Adoption",
    "tier": "executive",
    "description": "Composite index measuring AI deployment depth and breadth across PortCos, weighted by revenue.",
    "business_value": "Single adoption health score enabling portfolio-wide AI progress tracking.",
    "formula": "sum(portco_adoption_score * portco_revenue_weight) / sum(portco_revenue_weight)",
    "unit": "score_0_100",
    "aggregation": "weighted_average",
    "frequency": "monthly",
    "required_facts": ["portco_adoption_score", "portco_revenue_weight"],
    "derived_facts": [],
    "required_documents": ["project_portfolio", "operations"],
    "dependencies": ["portco_adoption_score", "portco_revenue_weight"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 85, "good": 70, "warning": 55, "critical": 40},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["cxo", "operating_partner"],
    "dashboard_visibility": ["executive_dashboard", "adoption_dashboard"],
    "example_calculation": "3 portcos: scores 76,62,81 weighted by revenue => composite=71/100",
    "status": "active"
},

"active_ai_users": {
    "name": "Active AI Users",
    "category": "User Adoption",
    "tier": "operational",
    "description": "Total employees with at least 5 meaningful AI tool interactions per week across portfolio.",
    "business_value": "Measures real workforce engagement with AI tools vs mere license allocation.",
    "formula": "count(employees WHERE weekly_ai_interactions >= 5)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "weekly",
    "required_facts": ["employee_id", "weekly_ai_interactions"],
    "derived_facts": [],
    "required_documents": ["telemetry", "hr"],
    "dependencies": ["weekly_ai_interactions"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 3000, "good": 2000, "warning": 1000, "critical": 500},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["operating_partner", "technology_lead"],
    "dashboard_visibility": ["adoption_dashboard", "operations_dashboard"],
    "example_calculation": "2772 employees with >=5 weekly interactions => active_ai_users=2772",
    "status": "active"
},

"percent_ai_in_production": {
    "name": "% AI in Production",
    "category": "Project Portfolio",
    "tier": "operational",
    "description": "Ratio of approved AI use cases currently in a live production state.",
    "business_value": "Tracks conversion from AI experimentation to value-generating production deployments.",
    "formula": "projects_in_production / total_approved_ai_projects * 100",
    "unit": "percentage",
    "aggregation": "portfolio_weighted_average",
    "frequency": "monthly",
    "required_facts": ["projects_in_production", "total_approved_ai_projects"],
    "derived_facts": [],
    "required_documents": ["project_portfolio"],
    "dependencies": ["projects_in_production", "total_approved_ai_projects"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 70, "good": 50, "warning": 30, "critical": 15},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["technology_lead", "operating_partner"],
    "dashboard_visibility": ["adoption_dashboard", "operations_dashboard"],
    "example_calculation": "18 live / 37 approved => 48.6% (technology view shows 64%)",
    "status": "active"
},

"ai_maturity_score": {
    "name": "AI Maturity Score",
    "category": "Maturity",
    "tier": "executive",
    "description": "Cross-portfolio assessment of AI engineering culture, data readiness, and governance capability on a 5-point scale.",
    "business_value": "Provides PE-level composite view of long-term AI capability and risk.",
    "formula": "(strategic_alignment_score + technical_maturity_score + talent_readiness_score + governance_maturity_score) / 4",
    "unit": "score_0_5",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["strategic_alignment_score", "technical_maturity_score", "talent_readiness_score", "governance_maturity_score"],
    "derived_facts": [],
    "required_documents": ["governance", "project_portfolio", "hr"],
    "dependencies": ["strategic_alignment_score", "technical_maturity_score", "talent_readiness_score", "governance_maturity_score"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 4.5, "good": 3.5, "warning": 2.5, "critical": 1.5},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["cxo", "technology_lead"],
    "dashboard_visibility": ["executive_dashboard", "benchmark_dashboard"],
    "example_calculation": "strategic=4.1, technical=2.8, talent=3.3, governance=3.4 => avg=3.4",
    "status": "active"
},

"total_ai_spend": {
    "name": "Total AI Spend",
    "category": "FinOps",
    "tier": "operational",
    "description": "Year-to-date cloud, licensing, and compute costs for all AI initiatives across portfolio.",
    "business_value": "Provides full cost visibility enabling FinOps governance and budget control.",
    "formula": "cloud_spend + api_licensing_spend + storage_data_spend + talent_ai_teams_spend",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["cloud_spend", "api_licensing_spend", "storage_data_spend", "talent_ai_teams_spend"],
    "derived_facts": [],
    "required_documents": ["financial", "inventory"],
    "dependencies": ["cloud_spend", "api_licensing_spend", "storage_data_spend", "talent_ai_teams_spend"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 5000000, "good": 10000000, "warning": 15000000, "critical": 20000000},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["cfo", "operating_partner"],
    "dashboard_visibility": ["finops_dashboard"],
    "example_calculation": "cloud=6.4M, api=2.9M, storage=3.5M => total=12.8M",
    "status": "active"
},

"budget_adherence": {
    "name": "Budget Adherence",
    "category": "FinOps",
    "tier": "operational",
    "description": "Closeness of actual AI operational spend to forecasted budget, expressed as a percentage.",
    "business_value": "Ensures AI spending discipline and prevents cost overruns.",
    "formula": "(1 - abs(total_ai_spend - approved_ai_budget) / approved_ai_budget) * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["total_ai_spend", "approved_ai_budget"],
    "derived_facts": [],
    "required_documents": ["financial"],
    "dependencies": ["total_ai_spend", "approved_ai_budget"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 98, "good": 92, "warning": 85, "critical": 70},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cfo", "operating_partner"],
    "dashboard_visibility": ["finops_dashboard"],
    "example_calculation": "spend=12.8M, budget=13M => adherence=98.5%",
    "status": "active"
},

"cost_per_outcome": {
    "name": "Cost per AI Outcome",
    "category": "FinOps",
    "tier": "operational",
    "description": "Normalized cost per meaningful business result (e.g. ticket resolved, sales assist completed) from AI systems.",
    "business_value": "Enables unit economics benchmarking and identifies inefficient AI deployments.",
    "formula": "total_ai_spend / total_ai_successful_outcomes",
    "unit": "USD",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["total_ai_spend", "total_ai_successful_outcomes"],
    "derived_facts": [],
    "required_documents": ["financial", "telemetry", "operations"],
    "dependencies": ["total_ai_spend", "total_ai_successful_outcomes"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 0.20, "good": 0.42, "warning": 0.80, "critical": 2.00},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.85},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["cfo", "technology_lead"],
    "dashboard_visibility": ["finops_dashboard", "operations_dashboard"],
    "example_calculation": "spend=12.8M, outcomes=30.5M => $0.42 per outcome",
    "status": "active"
},

"ai_governance_score": {
    "name": "AI Governance Score",
    "category": "Governance",
    "tier": "executive",
    "description": "Composite risk metric evaluating policy adherence, audit readiness, and model risk management.",
    "business_value": "Provides PE-level governance assurance and regulatory risk visibility.",
    "formula": "(data_privacy_compliance * 0.40 + model_bias_risk_score * 0.30 + regulatory_readiness * 0.30)",
    "unit": "score_0_100",
    "aggregation": "weighted_average",
    "frequency": "monthly",
    "required_facts": ["data_privacy_compliance", "model_bias_risk_score", "regulatory_readiness"],
    "derived_facts": [],
    "required_documents": ["governance", "audit"],
    "dependencies": ["data_privacy_compliance", "model_bias_risk_score", "regulatory_readiness"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 90, "good": 75, "warning": 60, "critical": 40},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["cxo", "compliance_lead"],
    "dashboard_visibility": ["executive_dashboard", "governance_dashboard"],
    "example_calculation": "privacy=76, bias=71, readiness=68 => score=72.1",
    "status": "active"
},

"policy_compliance_rate": {
    "name": "Policy Compliance Rate",
    "category": "Governance",
    "tier": "operational",
    "description": "Percentage of employees and vendors adhering to the Global AI Acceptable Use Policy.",
    "business_value": "Ensures organizational AI usage aligns with legal, ethical, and regulatory standards.",
    "formula": "compliant_entities / total_entities * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["compliant_entities", "total_entities"],
    "derived_facts": [],
    "required_documents": ["governance", "hr", "audit"],
    "dependencies": ["compliant_entities", "total_entities"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 98, "good": 92, "warning": 80, "critical": 65},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["compliance_lead", "operating_partner"],
    "dashboard_visibility": ["governance_dashboard"],
    "example_calculation": "9800 compliant / 10000 total => 98.0%",
    "status": "active"
},

"ai_incident_rate": {
    "name": "AI Incident Rate (Critical)",
    "category": "Governance",
    "tier": "operational",
    "description": "Count of high-impact AI failures or policy violations in the current month.",
    "business_value": "Early warning signal for AI reliability failures with reputational or financial consequences.",
    "formula": "count(incidents WHERE severity IN ['critical','high'] AND period = current_month)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["incident_id", "incident_severity", "incident_period"],
    "derived_facts": [],
    "required_documents": ["governance", "audit", "telemetry"],
    "dependencies": ["incident_severity"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 0, "good": 2, "warning": 5, "critical": 10},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead", "compliance_lead"],
    "dashboard_visibility": ["governance_dashboard", "operations_dashboard"],
    "example_calculation": "2 critical incidents in month => ai_incident_rate=2",
    "status": "active"
},

"portfolio_benchmark_score": {
    "name": "Portfolio Benchmark Score",
    "category": "Benchmarking",
    "tier": "executive",
    "description": "Nexus AI maturity score relative to industry-matched PE firm benchmarks, expressed as a percentile.",
    "business_value": "Provides LP-facing evidence of portfolio's AI leadership relative to peers.",
    "formula": "percentile_rank(portfolio_avg_maturity_score, benchmark_distribution)",
    "unit": "percentile",
    "aggregation": "latest_value",
    "frequency": "quarterly",
    "required_facts": ["portfolio_avg_maturity_score", "benchmark_distribution"],
    "derived_facts": [],
    "required_documents": ["benchmark", "board_deck"],
    "dependencies": ["portfolio_avg_maturity_score"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 90, "good": 75, "warning": 50, "critical": 25},
    "data_quality": {"minimum_coverage": 70, "confidence_threshold": 0.80},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cxo"],
    "dashboard_visibility": ["executive_dashboard", "benchmark_dashboard"],
    "example_calculation": "portfolio score=3.9x ROI vs industry median=2.4x => Top 15%",
    "status": "active"
},

"industry_benchmark_ratio": {
    "name": "Industry Benchmark Ratio",
    "category": "Benchmarking",
    "tier": "executive",
    "description": "Ratio of portfolio average ROI to industry median ROI from peer PE benchmark panel.",
    "business_value": "Enables LP-ready narrative on AI alpha generation versus sector median.",
    "formula": "portfolio_avg_roi / industry_median_roi",
    "unit": "ratio",
    "aggregation": "latest_value",
    "frequency": "quarterly",
    "required_facts": ["portfolio_avg_roi", "industry_median_roi"],
    "derived_facts": [],
    "required_documents": ["benchmark", "financial"],
    "dependencies": ["portfolio_avg_roi", "industry_median_roi"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 2.0, "good": 1.5, "warning": 1.1, "critical": 0.9},
    "data_quality": {"minimum_coverage": 70, "confidence_threshold": 0.80},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cxo", "operating_partner"],
    "dashboard_visibility": ["benchmark_dashboard"],
    "example_calculation": "portfolio_roi=3.9x, industry_median=2.4x => ratio=1.625",
    "status": "active"
},

"direct_ai_revenue": {
    "name": "Direct AI Revenue",
    "category": "Revenue Growth",
    "tier": "operational",
    "description": "Revenue from products or features where AI is the primary value driver.",
    "business_value": "Isolates pure AI product revenue for product-level accountability.",
    "formula": "sum(revenue_lines WHERE ai_attribution_type = 'direct')",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["revenue_line_amount", "ai_attribution_type"],
    "derived_facts": [],
    "required_documents": ["financial", "crm"],
    "dependencies": ["ai_attribution_type"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 5000000, "good": 2000000, "warning": 500000, "critical": 0},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.90},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["business_lead", "cxo"],
    "dashboard_visibility": ["revenue_dashboard"],
    "example_calculation": "direct AI product lines summed => $14.1M",
    "status": "active"
},

"ai_assisted_revenue": {
    "name": "AI-Assisted Revenue",
    "category": "Revenue Growth",
    "tier": "operational",
    "description": "Revenue from deals or renewals where AI tools materially assisted sales or customer success workflows.",
    "business_value": "Captures AI's indirect revenue contribution through sales acceleration.",
    "formula": "sum(revenue_lines WHERE ai_attribution_type = 'assisted')",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["revenue_line_amount", "ai_attribution_type"],
    "derived_facts": [],
    "required_documents": ["financial", "crm"],
    "dependencies": ["ai_attribution_type"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 3000000, "good": 1000000, "warning": 200000, "critical": 0},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.85},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["business_lead"],
    "dashboard_visibility": ["revenue_dashboard"],
    "example_calculation": "assisted AI sales lines => $6.4M",
    "status": "active"
},

"pipeline_influenced_revenue": {
    "name": "Pipeline Influenced Revenue",
    "category": "Revenue Growth",
    "tier": "operational",
    "description": "Revenue from pipeline opportunities that were generated or materially influenced by AI-driven marketing or outreach.",
    "business_value": "Measures AI's contribution to top-of-funnel revenue generation.",
    "formula": "sum(revenue_lines WHERE ai_attribution_type = 'pipeline_influenced')",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["revenue_line_amount", "ai_attribution_type"],
    "derived_facts": [],
    "required_documents": ["financial", "crm"],
    "dependencies": ["ai_attribution_type"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 10000000, "good": 5000000, "warning": 1000000, "critical": 0},
    "data_quality": {"minimum_coverage": 75, "confidence_threshold": 0.80},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["business_lead"],
    "dashboard_visibility": ["revenue_dashboard"],
    "example_calculation": "pipeline AI attribution lines => $18.9M",
    "status": "active"
},

"cross_sell_uplift": {
    "name": "Cross-Sell Uplift",
    "category": "Revenue Growth",
    "tier": "operational",
    "description": "Incremental revenue from cross-sell opportunities enabled by AI-driven customer intelligence.",
    "business_value": "Quantifies AI's contribution to customer expansion revenue.",
    "formula": "cross_sell_revenue_with_ai - cross_sell_revenue_baseline",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["cross_sell_revenue_with_ai", "cross_sell_revenue_baseline"],
    "derived_facts": [],
    "required_documents": ["crm", "financial"],
    "dependencies": ["cross_sell_revenue_with_ai", "cross_sell_revenue_baseline"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 2000000, "good": 500000, "warning": 100000, "critical": 0},
    "data_quality": {"minimum_coverage": 75, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["business_lead"],
    "dashboard_visibility": ["revenue_dashboard"],
    "example_calculation": "cross_sell_ai=5M, baseline=3.5M => uplift=1.5M",
    "status": "active"
},

"adoption_yoy_growth": {
    "name": "Adoption YoY Growth",
    "category": "Adoption",
    "tier": "operational",
    "description": "Year-over-year percentage growth in portfolio-wide AI adoption score.",
    "business_value": "Tracks momentum of AI adoption maturity over time.",
    "formula": "(adoption_score_current_year - adoption_score_prior_year) / adoption_score_prior_year * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "annual",
    "required_facts": ["adoption_score_current_year", "adoption_score_prior_year"],
    "derived_facts": [],
    "required_documents": ["project_portfolio", "operations"],
    "dependencies": ["adoption_score_current_year", "adoption_score_prior_year"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 30, "good": 15, "warning": 5, "critical": 0},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.85},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["operating_partner"],
    "dashboard_visibility": ["adoption_dashboard"],
    "example_calculation": "score_prior=55, score_current=71 => YoY growth=29.1%",
    "status": "active"
},

"total_ai_projects": {
    "name": "Total AI Projects",
    "category": "Project Portfolio",
    "tier": "operational",
    "description": "Aggregate count of all AI initiatives across all pipeline stages in the portfolio.",
    "business_value": "Provides complete pipeline visibility for investment and resource planning.",
    "formula": "count(projects WHERE ai_flag = true)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["project_id", "ai_flag"],
    "derived_facts": [],
    "required_documents": ["project_portfolio"],
    "dependencies": ["ai_flag"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 100, "good": 60, "warning": 30, "critical": 10},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead", "operating_partner"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "156 AI projects across all stages",
    "status": "active"
},

"projects_in_production": {
    "name": "Projects in Production",
    "category": "Project Portfolio",
    "tier": "operational",
    "description": "Count of AI projects currently live in production environments.",
    "business_value": "Measures conversion from pilots to value-generating production deployments.",
    "formula": "count(projects WHERE project_stage = 'production')",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["project_id", "project_stage"],
    "derived_facts": [],
    "required_documents": ["project_portfolio", "telemetry"],
    "dependencies": ["project_stage"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 60, "good": 40, "warning": 20, "critical": 5},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "53 projects in production state",
    "status": "active"
},

"projects_in_poc": {
    "name": "Projects in PoC / Pilot",
    "category": "Project Portfolio",
    "tier": "operational",
    "description": "Count of AI projects currently in proof-of-concept or pilot stage.",
    "business_value": "Tracks the pipeline feeding future production deployments.",
    "formula": "count(projects WHERE project_stage IN ['poc', 'pilot'])",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["project_id", "project_stage"],
    "derived_facts": [],
    "required_documents": ["project_portfolio"],
    "dependencies": ["project_stage"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 20, "good": 10, "warning": 5, "critical": 0},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "12 projects in PoC/Pilot stage",
    "status": "active"
},

"stalled_projects": {
    "name": "Stalled / Deprioritized Projects",
    "category": "Project Portfolio",
    "tier": "operational",
    "description": "Count of AI projects with no activity for 30+ days or formally deprioritized.",
    "business_value": "Surfaces resource waste and pipeline blockages requiring intervention.",
    "formula": "count(projects WHERE project_stage IN ['stalled','deprioritized'] OR days_since_last_update >= 30)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["project_id", "project_stage", "days_since_last_update"],
    "derived_facts": [],
    "required_documents": ["project_portfolio"],
    "dependencies": ["project_stage", "days_since_last_update"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 2, "good": 5, "warning": 10, "critical": 20},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead", "operating_partner"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "3 stalled projects identified",
    "status": "active"
},

"production_ratio": {
    "name": "Production Ratio",
    "category": "Project Portfolio",
    "tier": "operational",
    "description": "Ratio of production projects to total PoC/Pilot projects, measuring pipeline conversion efficiency.",
    "business_value": "Identifies portfolio velocity in converting experiments to production value.",
    "formula": "projects_in_production / projects_in_poc",
    "unit": "ratio",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["projects_in_production", "projects_in_poc"],
    "derived_facts": [],
    "required_documents": ["project_portfolio"],
    "dependencies": ["projects_in_production", "projects_in_poc"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 4.0, "good": 2.5, "warning": 1.5, "critical": 0.5},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "53 production / 12 poc => ratio=4.4",
    "status": "active"
},

"power_user_ratio": {
    "name": "Power User Ratio",
    "category": "User Adoption",
    "tier": "operational",
    "description": "Percentage of active AI users who engage with AI tools more than 20 times per week.",
    "business_value": "Identifies depth of AI integration in daily workflows beyond surface adoption.",
    "formula": "count(users WHERE weekly_ai_interactions > 20) / active_ai_users * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "weekly",
    "required_facts": ["weekly_ai_interactions", "active_ai_users"],
    "derived_facts": [],
    "required_documents": ["telemetry", "hr"],
    "dependencies": ["weekly_ai_interactions", "active_ai_users"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 40, "good": 25, "warning": 15, "critical": 5},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead", "operating_partner"],
    "dashboard_visibility": ["adoption_dashboard"],
    "example_calculation": "844 power users / 2772 active => 30.4%",
    "status": "active"
},

"dau_mau_intensity": {
    "name": "DAU / MAU Intensity",
    "category": "User Adoption",
    "tier": "operational",
    "description": "Total employees actively interacting with AI production tools on a daily basis.",
    "business_value": "Measures depth of daily AI engagement beyond weekly adoption metrics.",
    "formula": "count(employees WHERE daily_ai_interactions >= 1 AND interaction_date = current_date)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "daily",
    "required_facts": ["daily_ai_interactions", "interaction_date"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["daily_ai_interactions"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 3000, "good": 2000, "warning": 1000, "critical": 500},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["adoption_dashboard"],
    "example_calculation": "2800 employees with daily AI interactions",
    "status": "active"
},

"copilot_adoption": {
    "name": "Copilot Adoption",
    "category": "User Adoption",
    "tier": "operational",
    "description": "Count of employees actively using AI copilot tools (coding assistants, writing assistants) at least weekly.",
    "business_value": "Tracks adoption of productivity-enhancing AI assistants across portfolio workforce.",
    "formula": "count(employees WHERE copilot_tool_weekly_sessions >= 1)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "weekly",
    "required_facts": ["copilot_tool_weekly_sessions"],
    "derived_facts": [],
    "required_documents": ["telemetry", "hr"],
    "dependencies": ["copilot_tool_weekly_sessions"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 1500, "good": 1000, "warning": 500, "critical": 100},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["adoption_dashboard"],
    "example_calculation": "1200 employees with weekly copilot sessions",
    "status": "active"
},

"custom_agent_adoption": {
    "name": "Custom Agent Adoption",
    "category": "User Adoption",
    "tier": "operational",
    "description": "Count of employees actively using custom-built AI agents deployed by PortCos.",
    "business_value": "Measures adoption of bespoke AI automation beyond off-the-shelf tools.",
    "formula": "count(employees WHERE custom_agent_weekly_sessions >= 1)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "weekly",
    "required_facts": ["custom_agent_weekly_sessions"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["custom_agent_weekly_sessions"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 1000, "good": 600, "warning": 200, "critical": 50},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["adoption_dashboard"],
    "example_calculation": "900 employees using custom agents weekly",
    "status": "active"
},

"embedded_analytics_adoption": {
    "name": "Embedded Analytics Adoption",
    "category": "User Adoption",
    "tier": "operational",
    "description": "Count of employees actively using AI-powered embedded analytics features in business applications.",
    "business_value": "Tracks data-driven decision making enabled by AI-powered analytics.",
    "formula": "count(employees WHERE embedded_analytics_weekly_sessions >= 1)",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "weekly",
    "required_facts": ["embedded_analytics_weekly_sessions"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["embedded_analytics_weekly_sessions"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 800, "good": 500, "warning": 200, "critical": 50},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead", "business_lead"],
    "dashboard_visibility": ["adoption_dashboard"],
    "example_calculation": "700 employees with weekly embedded analytics sessions",
    "status": "active"
},

"strategic_alignment_score": {
    "name": "Strategic Alignment Score",
    "category": "Maturity",
    "tier": "operational",
    "description": "Assessment of how well AI initiatives align with each PortCo's core business strategy and goals.",
    "business_value": "Ensures AI investments support business objectives rather than tech-for-tech-sake.",
    "formula": "average(portco_strategic_alignment_rating) WHERE portco_strategic_alignment_rating IN [0,5]",
    "unit": "score_0_5",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["portco_strategic_alignment_rating"],
    "derived_facts": [],
    "required_documents": ["governance", "board_deck"],
    "dependencies": ["portco_strategic_alignment_rating"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 4.5, "good": 3.5, "warning": 2.5, "critical": 1.5},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["cxo", "operating_partner"],
    "dashboard_visibility": ["executive_dashboard"],
    "example_calculation": "portfolio average strategic alignment = 4.1/5",
    "status": "active"
},

"technical_maturity_score": {
    "name": "Technical Maturity Score",
    "category": "Maturity",
    "tier": "operational",
    "description": "Assessment of MLOps rigor, data infrastructure quality, and AI engineering practices.",
    "business_value": "Identifies technical gaps that limit AI scalability and reliability.",
    "formula": "average(portco_technical_maturity_rating) WHERE portco_technical_maturity_rating IN [0,5]",
    "unit": "score_0_5",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["portco_technical_maturity_rating"],
    "derived_facts": [],
    "required_documents": ["governance", "project_portfolio"],
    "dependencies": ["portco_technical_maturity_rating"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 4.5, "good": 3.5, "warning": 2.5, "critical": 1.5},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "portfolio average technical maturity = 2.8/5",
    "status": "active"
},

"talent_readiness_score": {
    "name": "Talent Readiness Score",
    "category": "Maturity",
    "tier": "operational",
    "description": "Assessment of workforce AI skill levels, training completion, and AI talent density.",
    "business_value": "Identifies human capital gaps that constrain AI adoption velocity.",
    "formula": "average(portco_talent_readiness_rating) WHERE portco_talent_readiness_rating IN [0,5]",
    "unit": "score_0_5",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["portco_talent_readiness_rating"],
    "derived_facts": [],
    "required_documents": ["hr", "governance"],
    "dependencies": ["portco_talent_readiness_rating"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 4.5, "good": 3.5, "warning": 2.5, "critical": 1.5},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["operating_partner", "hr_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "portfolio average talent readiness = 3.3/5",
    "status": "active"
},

"governance_maturity_score": {
    "name": "Governance Maturity Score",
    "category": "Maturity",
    "tier": "operational",
    "description": "Assessment of AI governance frameworks, policy completeness, and audit trail quality.",
    "business_value": "Measures readiness to govern AI at scale with PE-required compliance standards.",
    "formula": "average(portco_governance_maturity_rating) WHERE portco_governance_maturity_rating IN [0,5]",
    "unit": "score_0_5",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["portco_governance_maturity_rating"],
    "derived_facts": [],
    "required_documents": ["governance", "audit"],
    "dependencies": ["portco_governance_maturity_rating"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 4.5, "good": 3.5, "warning": 2.5, "critical": 1.5},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["compliance_lead", "cxo"],
    "dashboard_visibility": ["governance_dashboard"],
    "example_calculation": "portfolio average governance maturity = 3.4/5",
    "status": "active"
},

"spend_by_model_family": {
    "name": "Spend by Model Family",
    "category": "FinOps",
    "tier": "operational",
    "description": "Percentage cost distribution of total AI spend across commercial and open-source model families.",
    "business_value": "Enables model vendor concentration risk management and cost optimization.",
    "formula": "model_family_spend / total_ai_spend * 100",
    "unit": "percentage",
    "aggregation": "latest_value",
    "frequency": "monthly",
    "required_facts": ["model_family_spend", "total_ai_spend"],
    "derived_facts": [],
    "required_documents": ["financial", "inventory"],
    "dependencies": ["model_family_spend", "total_ai_spend"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 40, "good": 60, "warning": 75, "critical": 90},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["technology_lead", "cfo"],
    "dashboard_visibility": ["finops_dashboard"],
    "example_calculation": "OpenAI=62%, Anthropic=18%, Llama=14%, Other=6%",
    "status": "active"
},

"forecasted_ai_spend": {
    "name": "Forecasted AI Spend",
    "category": "FinOps",
    "tier": "operational",
    "description": "Projected end-of-year AI spend based on current token usage velocity and committed contracts.",
    "business_value": "Enables proactive budget management and prevents year-end overspend surprises.",
    "formula": "committed_spend + (current_run_rate_spend * remaining_months_in_year)",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["committed_spend", "current_run_rate_spend", "remaining_months_in_year"],
    "derived_facts": [],
    "required_documents": ["financial", "inventory"],
    "dependencies": ["committed_spend", "current_run_rate_spend"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 15000000, "good": 18000000, "warning": 22000000, "critical": 30000000},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cfo"],
    "dashboard_visibility": ["finops_dashboard"],
    "example_calculation": "committed=14.1M + run_rate=4.1M*1mo remaining => forecasted=18.2M",
    "status": "active"
},

"budget_variance": {
    "name": "Budget Variance",
    "category": "FinOps",
    "tier": "operational",
    "description": "Absolute and percentage difference between actual AI spend and approved AI budget for the period.",
    "business_value": "Provides early warning for budget overruns requiring governance intervention.",
    "formula": "total_ai_spend - approved_ai_budget",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["total_ai_spend", "approved_ai_budget"],
    "derived_facts": [],
    "required_documents": ["financial"],
    "dependencies": ["total_ai_spend", "approved_ai_budget"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 0, "good": 500000, "warning": 1000000, "critical": 2000000},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "insufficient_data",
    "owner_persona": ["cfo"],
    "dashboard_visibility": ["finops_dashboard"],
    "example_calculation": "spend=12.8M, budget=13.3M => variance=-0.5M (under budget)",
    "status": "active"
},

"cloud_spend": {
    "name": "Cloud Compute Spend",
    "category": "FinOps",
    "tier": "operational",
    "description": "Total cloud infrastructure costs for AI workloads including GPU instances and storage.",
    "business_value": "Largest cost driver for AI — requires dedicated visibility and optimization.",
    "formula": "sum(cloud_invoices WHERE workload_tag = 'ai')",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["cloud_invoice_amount", "workload_tag"],
    "derived_facts": [],
    "required_documents": ["financial", "inventory"],
    "dependencies": ["workload_tag"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 3000000, "good": 6000000, "warning": 9000000, "critical": 12000000},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cfo", "technology_lead"],
    "dashboard_visibility": ["finops_dashboard"],
    "example_calculation": "GPU+infra cloud bills tagged AI => $6.4M",
    "status": "active"
},

"api_licensing_spend": {
    "name": "API Licensing Spend",
    "category": "FinOps",
    "tier": "operational",
    "description": "Total spend on AI API access and model licensing from commercial providers.",
    "business_value": "Tracks third-party AI dependency costs and enables vendor negotiation leverage.",
    "formula": "sum(vendor_invoices WHERE spend_category = 'api_licensing')",
    "unit": "USD",
    "aggregation": "sum",
    "frequency": "monthly",
    "required_facts": ["vendor_invoice_amount", "spend_category"],
    "derived_facts": [],
    "required_documents": ["financial", "inventory"],
    "dependencies": ["spend_category"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 1000000, "good": 2500000, "warning": 4000000, "critical": 6000000},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cfo"],
    "dashboard_visibility": ["finops_dashboard"],
    "example_calculation": "OpenAI + Anthropic API invoices => $2.9M",
    "status": "active"
},

"availability_uptime": {
    "name": "System Availability (Uptime)",
    "category": "Reliability",
    "tier": "operational",
    "description": "System uptime percentage across all critical AI-driven infrastructure endpoints.",
    "business_value": "Ensures AI systems meet SLA commitments and do not disrupt business operations.",
    "formula": "(total_minutes_in_period - total_downtime_minutes) / total_minutes_in_period * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["total_minutes_in_period", "total_downtime_minutes"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["total_downtime_minutes"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "sre_standards"},
    "thresholds": {"excellent": 99.9, "good": 99.5, "warning": 99.0, "critical": 98.0},
    "data_quality": {"minimum_coverage": 99, "confidence_threshold": 0.99},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "downtime=4.3min in 43800min period => 99.99%",
    "status": "active"
},

"api_success_rate": {
    "name": "API Success Rate",
    "category": "Reliability",
    "tier": "operational",
    "description": "Percentage of AI API calls completing successfully without 5xx errors.",
    "business_value": "Monitors AI endpoint reliability essential for user experience and business continuity.",
    "formula": "count(api_calls WHERE status_code < 500) / count(api_calls) * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "daily",
    "required_facts": ["api_call_id", "api_status_code"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["api_status_code"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "sre_standards"},
    "thresholds": {"excellent": 99.9, "good": 99.5, "warning": 98.0, "critical": 95.0},
    "data_quality": {"minimum_coverage": 99, "confidence_threshold": 0.99},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "9998 success / 10000 calls => 99.98%",
    "status": "active"
},

"p95_latency": {
    "name": "P95 Latency",
    "category": "Reliability",
    "tier": "operational",
    "description": "95th percentile response time for consumer-facing LLM inference requests.",
    "business_value": "Ensures AI system responsiveness meets user experience and SLA thresholds.",
    "formula": "percentile(api_response_time_ms, 95)",
    "unit": "milliseconds",
    "aggregation": "average",
    "frequency": "daily",
    "required_facts": ["api_response_time_ms"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["api_response_time_ms"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "sre_standards"},
    "thresholds": {"excellent": 500, "good": 1500, "warning": 3000, "critical": 5000},
    "data_quality": {"minimum_coverage": 99, "confidence_threshold": 0.99},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "P95 across all LLM endpoints = 1420ms",
    "status": "active"
},

"error_rate": {
    "name": "Error Rate",
    "category": "Reliability",
    "tier": "operational",
    "description": "Percentage of AI API requests resulting in uncaught exceptions or 5xx server errors.",
    "business_value": "Primary reliability health signal for AI infrastructure teams.",
    "formula": "count(api_calls WHERE status_code >= 500) / count(api_calls) * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "daily",
    "required_facts": ["api_call_id", "api_status_code"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["api_status_code"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "sre_standards"},
    "thresholds": {"excellent": 0.05, "good": 0.1, "warning": 0.5, "critical": 2.0},
    "data_quality": {"minimum_coverage": 99, "confidence_threshold": 0.99},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "8 errors / 10000 calls => 0.08%",
    "status": "active"
},

"hallucination_rate": {
    "name": "Hallucination Detection Rate",
    "category": "Governance",
    "tier": "operational",
    "description": "Percentage of AI model outputs flagged as factually incorrect or fabricated by automated detection systems.",
    "business_value": "Critical quality signal for AI reliability and trust, especially in financial and legal contexts.",
    "formula": "count(outputs WHERE hallucination_flag = true) / count(evaluated_outputs) * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "daily",
    "required_facts": ["evaluated_output_id", "hallucination_flag"],
    "derived_facts": [],
    "required_documents": ["telemetry", "audit"],
    "dependencies": ["hallucination_flag"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 0.5, "good": 1.0, "warning": 3.0, "critical": 5.0},
    "data_quality": {"minimum_coverage": 85, "confidence_threshold": 0.85},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead", "compliance_lead"],
    "dashboard_visibility": ["governance_dashboard", "operations_dashboard"],
    "example_calculation": "2.4% of evaluated outputs flagged as hallucinations",
    "status": "active"
},

"fallback_rate": {
    "name": "Fallback Rate",
    "category": "Reliability",
    "tier": "operational",
    "description": "Percentage of AI requests that fall back to a secondary system or human escalation due to primary model failure.",
    "business_value": "Indicates primary model reliability and efficiency of fallback architecture.",
    "formula": "count(requests WHERE fallback_triggered = true) / count(requests) * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "daily",
    "required_facts": ["request_id", "fallback_triggered"],
    "derived_facts": [],
    "required_documents": ["telemetry"],
    "dependencies": ["fallback_triggered"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 0.05, "good": 0.5, "warning": 1.5, "critical": 5.0},
    "data_quality": {"minimum_coverage": 95, "confidence_threshold": 0.95},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "14 fallbacks / 10000 requests => 0.14%",
    "status": "active"
},

"mttr": {
    "name": "MTTR (Incident Response)",
    "category": "Reliability",
    "tier": "operational",
    "description": "Mean time to recover from AI-specific service degradation incidents.",
    "business_value": "Measures operational maturity and resilience of AI infrastructure teams.",
    "formula": "average(incident_resolution_time_minutes) WHERE incident_type = 'ai_service_degradation'",
    "unit": "minutes",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["incident_id", "incident_resolution_time_minutes", "incident_type"],
    "derived_facts": [],
    "required_documents": ["telemetry", "audit"],
    "dependencies": ["incident_resolution_time_minutes", "incident_type"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "sre_standards"},
    "thresholds": {"excellent": 15, "good": 30, "warning": 60, "critical": 120},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead"],
    "dashboard_visibility": ["operations_dashboard"],
    "example_calculation": "average recovery across 4 incidents = 24 minutes",
    "status": "active"
},

"data_privacy_compliance": {
    "name": "Data Privacy Compliance",
    "category": "Governance",
    "tier": "operational",
    "description": "Compliance score measuring adherence to data privacy regulations (GDPR, CCPA) in AI data pipelines.",
    "business_value": "Reduces regulatory risk and protects LP/PortCo from privacy violation fines.",
    "formula": "compliant_data_pipelines / total_data_pipelines * 100",
    "unit": "score_0_100",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["compliant_data_pipelines", "total_data_pipelines"],
    "derived_facts": [],
    "required_documents": ["governance", "audit"],
    "dependencies": ["compliant_data_pipelines", "total_data_pipelines"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 98, "good": 90, "warning": 75, "critical": 60},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["compliance_lead"],
    "dashboard_visibility": ["governance_dashboard"],
    "example_calculation": "76 compliant / 100 pipelines => 76/100 score",
    "status": "active"
},

"regulatory_readiness": {
    "name": "Regulatory Readiness",
    "category": "Governance",
    "tier": "operational",
    "description": "Assessment of preparedness for current and upcoming AI regulations (EU AI Act, SEC AI disclosure).",
    "business_value": "Proactively de-risks portfolio from emerging AI compliance obligations.",
    "formula": "average(portco_regulatory_readiness_rating) WHERE portco_regulatory_readiness_rating IN [0,100]",
    "unit": "score_0_100",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["portco_regulatory_readiness_rating"],
    "derived_facts": [],
    "required_documents": ["governance", "audit"],
    "dependencies": ["portco_regulatory_readiness_rating"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 90, "good": 75, "warning": 60, "critical": 40},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.80},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["compliance_lead", "cxo"],
    "dashboard_visibility": ["governance_dashboard"],
    "example_calculation": "portfolio avg regulatory readiness = 68/100",
    "status": "active"
},

"human_review_coverage": {
    "name": "Human Review Coverage",
    "category": "Governance",
    "tier": "operational",
    "description": "Percentage of AI outputs subjected to human-in-the-loop audit for high-criticality decisions.",
    "business_value": "Ensures human oversight is maintained for AI decisions with significant business or legal impact.",
    "formula": "count(outputs WHERE human_review_completed = true AND criticality = 'high') / count(outputs WHERE criticality = 'high') * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "monthly",
    "required_facts": ["output_id", "human_review_completed", "output_criticality"],
    "derived_facts": [],
    "required_documents": ["audit", "governance"],
    "dependencies": ["human_review_completed", "output_criticality"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 98, "good": 88, "warning": 70, "critical": 50},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["compliance_lead", "operating_partner"],
    "dashboard_visibility": ["governance_dashboard"],
    "example_calculation": "880 reviewed / 1000 high-criticality outputs => 88%",
    "status": "active"
},

"critical_incident_count": {
    "name": "Critical Incident Count",
    "category": "Governance",
    "tier": "operational",
    "description": "Total number of active or unresolved critical AI incidents including data leakage, drift, and hallucinations.",
    "business_value": "Tracks open risks requiring immediate escalation and remediation.",
    "formula": "count(incidents WHERE severity = 'critical' AND status != 'resolved')",
    "unit": "count",
    "aggregation": "sum",
    "frequency": "daily",
    "required_facts": ["incident_id", "incident_severity", "incident_status"],
    "derived_facts": [],
    "required_documents": ["governance", "audit", "telemetry"],
    "dependencies": ["incident_severity", "incident_status"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 0, "good": 1, "warning": 3, "critical": 5},
    "data_quality": {"minimum_coverage": 99, "confidence_threshold": 0.99},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["technology_lead", "compliance_lead"],
    "dashboard_visibility": ["governance_dashboard", "operations_dashboard"],
    "example_calculation": "2 unresolved critical incidents open",
    "status": "active"
},

"vendor_compliance": {
    "name": "Vendor Compliance",
    "category": "Governance",
    "tier": "operational",
    "description": "Percentage of third-party AI vendors meeting minimum PE-defined security and compliance requirements.",
    "business_value": "Manages third-party AI risk in the supply chain.",
    "formula": "count(vendors WHERE compliance_status = 'compliant') / count(vendors) * 100",
    "unit": "percentage",
    "aggregation": "average",
    "frequency": "quarterly",
    "required_facts": ["vendor_id", "compliance_status"],
    "derived_facts": [],
    "required_documents": ["governance", "audit"],
    "dependencies": ["compliance_status"],
    "benchmarking": {"enabled": False, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 98, "good": 90, "warning": 80, "critical": 65},
    "data_quality": {"minimum_coverage": 90, "confidence_threshold": 0.90},
    "missing_data_strategy": "use_worst_case",
    "owner_persona": ["compliance_lead"],
    "dashboard_visibility": ["governance_dashboard"],
    "example_calculation": "96.4% of third-party vendors compliant",
    "status": "active"
},

"adoption_velocity_rank": {
    "name": "Adoption Velocity Rank",
    "category": "Benchmarking",
    "tier": "executive",
    "description": "Portfolio percentile ranking on speed of AI adoption relative to PE benchmark panel.",
    "business_value": "Provides competitive intelligence on adoption pace vs peer PE firms.",
    "formula": "percentile_rank(portfolio_adoption_velocity, benchmark_adoption_velocity_distribution)",
    "unit": "percentile",
    "aggregation": "latest_value",
    "frequency": "quarterly",
    "required_facts": ["portfolio_adoption_velocity", "benchmark_adoption_velocity_distribution"],
    "derived_facts": [],
    "required_documents": ["benchmark"],
    "dependencies": ["portfolio_adoption_velocity"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 90, "good": 75, "warning": 50, "critical": 25},
    "data_quality": {"minimum_coverage": 70, "confidence_threshold": 0.80},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cxo"],
    "dashboard_visibility": ["benchmark_dashboard"],
    "example_calculation": "portfolio adoption velocity ranks at 92nd percentile",
    "status": "active"
},

"cost_efficiency_rank": {
    "name": "Cost Efficiency Rank",
    "category": "Benchmarking",
    "tier": "executive",
    "description": "Portfolio percentile ranking on AI cost efficiency relative to PE benchmark panel.",
    "business_value": "Validates FinOps discipline relative to peers and informs cost optimization targets.",
    "formula": "percentile_rank(portfolio_cost_per_outcome, benchmark_cost_efficiency_distribution)",
    "unit": "percentile",
    "aggregation": "latest_value",
    "frequency": "quarterly",
    "required_facts": ["portfolio_cost_per_outcome", "benchmark_cost_efficiency_distribution"],
    "derived_facts": [],
    "required_documents": ["benchmark", "financial"],
    "dependencies": ["portfolio_cost_per_outcome"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 90, "good": 75, "warning": 50, "critical": 25},
    "data_quality": {"minimum_coverage": 70, "confidence_threshold": 0.80},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cxo", "cfo"],
    "dashboard_visibility": ["benchmark_dashboard"],
    "example_calculation": "portfolio cost efficiency ranks at 88th percentile",
    "status": "active"
},

"governance_rank": {
    "name": "Governance Rank",
    "category": "Benchmarking",
    "tier": "executive",
    "description": "Portfolio percentile ranking on AI governance maturity relative to PE benchmark panel.",
    "business_value": "Demonstrates governance leadership to LPs and regulators.",
    "formula": "percentile_rank(ai_governance_score, benchmark_governance_distribution)",
    "unit": "percentile",
    "aggregation": "latest_value",
    "frequency": "quarterly",
    "required_facts": ["ai_governance_score", "benchmark_governance_distribution"],
    "derived_facts": [],
    "required_documents": ["benchmark", "governance"],
    "dependencies": ["ai_governance_score"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 90, "good": 75, "warning": 50, "critical": 25},
    "data_quality": {"minimum_coverage": 70, "confidence_threshold": 0.80},
    "missing_data_strategy": "use_last_known",
    "owner_persona": ["cxo", "compliance_lead"],
    "dashboard_visibility": ["benchmark_dashboard"],
    "example_calculation": "governance score ranks at 94th percentile",
    "status": "active"
},

"company_maturity_rank": {
    "name": "Company Maturity Rank",
    "category": "Benchmarking",
    "tier": "executive",
    "description": "Individual PortCo ranking by AI maturity score within the portfolio.",
    "business_value": "Identifies leaders and laggards for targeted operating partner support.",
    "formula": "rank(portco_ai_maturity_score) OVER (PARTITION BY portfolio ORDER BY portco_ai_maturity_score DESC)",
    "unit": "rank",
    "aggregation": "latest_value",
    "frequency": "quarterly",
    "required_facts": ["portco_ai_maturity_score"],
    "derived_facts": [],
    "required_documents": ["project_portfolio", "governance"],
    "dependencies": ["portco_ai_maturity_score"],
    "benchmarking": {"enabled": True, "benchmark_type": "portfolio", "benchmark_source": "internal"},
    "thresholds": {"excellent": 1, "good": 3, "warning": 5, "critical": 8},
    "data_quality": {"minimum_coverage": 80, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["operating_partner"],
    "dashboard_visibility": ["benchmark_dashboard"],
    "example_calculation": "#1 Precision Tech maturity=4.8, #2 Nexus Industrial=4.6",
    "status": "active"
},

"top_quartile_position": {
    "name": "Top Quartile Position",
    "category": "Benchmarking",
    "tier": "executive",
    "description": "Percentage of portfolio PortCos ranking in the top quartile of AI maturity within the industry benchmark.",
    "business_value": "LP-facing headline metric demonstrating portfolio AI leadership concentration.",
    "formula": "count(portcos WHERE industry_maturity_percentile >= 75) / count(portcos) * 100",
    "unit": "percentage",
    "aggregation": "latest_value",
    "frequency": "quarterly",
    "required_facts": ["portco_industry_maturity_percentile"],
    "derived_facts": [],
    "required_documents": ["benchmark"],
    "dependencies": ["portco_industry_maturity_percentile"],
    "benchmarking": {"enabled": True, "benchmark_type": "industry", "benchmark_source": "pe_benchmark_panel"},
    "thresholds": {"excellent": 50, "good": 30, "warning": 15, "critical": 5},
    "data_quality": {"minimum_coverage": 70, "confidence_threshold": 0.80},
    "missing_data_strategy": "exclude_portco",
    "owner_persona": ["cxo"],
    "dashboard_visibility": ["executive_dashboard", "benchmark_dashboard"],
    "example_calculation": "28% of PortCos in top quartile globally",
    "status": "active"
},

}

# Write all KPI YAMLs
for kpi_id, data in KPIS.items():
    data["kpi_id"] = kpi_id
    filepath = os.path.join(OUT, f"{kpi_id}.yaml")
    with open(filepath, "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

print(f"Written {len(KPIS)} KPI files.")
